# -*- coding: utf-8 -*-
"""modelos ARIMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SkBocKvSZUO7G0NPrmcqm4eDYCoAjtZQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, coint
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Upload Excel files for Nike, Coca-Cola, Amazon (5-min and 30-min)
print("Please upload Nike 5-min Excel file (e.g., PY - Nike - 5min.xlsx)")
nike_5m_upload = files.upload()
nike_5m_filename = list(nike_5m_upload.keys())[0]
nike_5m_df = pd.read_excel(nike_5m_filename)

print("Please upload Nike 30-min Excel file (e.g., PY - Nike - 30 min.xlsx)")
nike_30m_upload = files.upload()
nike_30m_filename = list(nike_30m_upload.keys())[0]
nike_30m_df = pd.read_excel(nike_30m_filename)

print("Please upload Coca-Cola 5-min Excel file (e.g., PY - CocaCola - 5 min.xlsx)")
cocacola_5m_upload = files.upload()
cocacola_5m_filename = list(cocacola_5m_upload.keys())[0]
cocacola_5m_df = pd.read_excel(cocacola_5m_filename)

print("Please upload Coca-Cola 30-min Excel file (e.g., PY - CocaCola - 30min.xlsx)")
cocacola_30m_upload = files.upload()
cocacola_30m_filename = list(cocacola_30m_upload.keys())[0]
cocacola_30m_df = pd.read_excel(cocacola_30m_filename)

print("Please upload Amazon 5-min Excel file (e.g., PY - Amazon - 5min.xlsx)")
amazon_5m_upload = files.upload()
amazon_5m_filename = list(amazon_5m_upload.keys())[0]
amazon_5m_df = pd.read_excel(amazon_5m_filename)

print("Please upload Amazon 30-min Excel file (e.g., PY - Amazon - 30 min.xlsx)")
amazon_30m_upload = files.upload()
amazon_30m_filename = list(amazon_30m_upload.keys())[0]
amazon_30m_df = pd.read_excel(amazon_30m_filename)

# Print available columns for verification
print("\nNike 5-min columns:", list(nike_5m_df.columns))
print("Nike 30-min columns:", list(nike_30m_df.columns))
print("Coca-Cola 5-min columns:", list(cocacola_5m_df.columns))
print("Coca-Cola 30-min columns:", list(cocacola_30m_df.columns))
print("Amazon 5-min columns:", list(amazon_5m_df.columns))
print("Amazon 30-min columns:", list(amazon_30m_df.columns))

# Ask user for the correct column name for closing prices
close_column = input("Please enter the column name containing closing prices (press Enter for 'Close'): ") or 'Close'

# Extract closing prices using user-specified column name
try:
    nike_5m_close = nike_5m_df[close_column]
    nike_30m_close = nike_30m_df[close_column]
    cocacola_5m_close = cocacola_5m_df[close_column]
    cocacola_30m_close = cocacola_30m_df[close_column]
    amazon_5m_close = amazon_5m_df[close_column]
    amazon_30m_close = amazon_30m_df[close_column]
except KeyError:
    print(f"Error: Column '{close_column}' not found in one or more DataFrames")
    print("Please check the column names and try again")
    raise

# Ensure all series have the same length
min_length = min(len(nike_5m_close), len(nike_30m_close), len(cocacola_5m_close),
                 len(cocacola_30m_close), len(amazon_5m_close), len(amazon_30m_close))
nike_5m_close = nike_5m_close[:min_length]
nike_30m_close = nike_30m_close[:min_length]
cocacola_5m_close = cocacola_5m_close[:min_length]
cocacola_30m_close = cocacola_30m_close[:min_length]
amazon_5m_close = amazon_5m_close[:min_length]
amazon_30m_close = amazon_30m_close[:min_length]

# Dictionary to store series for easier iteration
series_dict = {
    "Nike_5min": nike_5m_close,
    "Nike_30min": nike_30m_close,
    "CocaCola_5min": cocacola_5m_close,
    "CocaCola_30min": cocacola_30m_close,
    "Amazon_5min": amazon_5m_close,
    "Amazon_30min": amazon_30m_close
}

# Data validation
print("\nData Validation:")
for name, series in series_dict.items():
    print(f"{name}:")
    print(f"  Length: {len(series)}")
    print(f"  NaN count: {series.isna().sum()}")
    print(f"  Infinite values: {np.isinf(series).sum()}")
    print(f"  Variance: {series.var():.4f}")

# Check if min_length is sufficient
if min_length < 50:
    print("Warning: Data length is very short (%d). Cointegration tests may be unreliable." % min_length)

# Random Walk Test
def random_walk_test(series, name):
    print(f"\nRandom Walk Test for {name}:")
    diff = series.diff().dropna()
    if np.var(diff) < 1e-5:
        print(f"{name} resembles a random walk (low variance in differences).")
    else:
        print(f"{name} does not clearly exhibit random walk behavior.")

# Unit Root Test (ADF only)
def unit_root_test(series, name):
    print(f"\nUnit Root Test (ADF) for {name}:")
    adf_result = adfuller(series)
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

# Cointegration Test (Engle-Granger)
def cointegration_test(series1, series2, name1, name2):
    print(f"\nCointegration Test (Engle-Granger) between {name1} and {name2}:")
    try:
        score, p_value, _ = coint(series1, series2)
        print(f'Cointegration test statistic: {score:.4f}')
        print(f'p-value: {p_value:.4f}')
        if p_value < 0.05:
            print(f"Interpretation: {name1} and {name2} are cointegrated.")
        else:
            print(f"Interpretation: {name1} and {name2} are not cointegrated.")
    except Exception as e:
        print(f"Error in cointegration test: {e}")

# Function to find best ARIMA model
def find_best_arima(series, name, max_p=2, max_d=1, max_q=2):
    print(f"Fitting ARIMA for {name}...")
    best_aic = float('inf')
    best_order = None
    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except Exception as e:
                    print(f"  Failed ARIMA({p},{d},{q}) for {name}: {e}")
                    continue
    if best_order is None:
        print(f"Error: No valid ARIMA model found for {name}. Skipping.")
        return None
    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Perform tests and ARIMA modeling for all series
arima_orders = {}
arima_models = {}
print("\nStarting ARIMA modeling...")
for name, series in series_dict.items():
    random_walk_test(series, name)
    unit_root_test(series, name)
    order = find_best_arima(series, name)
    if order is None:
        arima_orders[name] = None
        arima_models[name] = None
        continue
    try:
        model = ARIMA(series, order=order).fit()
        arima_orders[name] = order
        arima_models[name] = model
        print(f"ARIMA model fitted for {name}.")
    except Exception as e:
        print(f"Error fitting final ARIMA model for {name}: {e}")
        arima_orders[name] = order
        arima_models[name] = None

# Forecast next 30 periods
forecast_steps = 30
forecasts = {}
print("\nGenerating forecasts...")
for name, model in arima_models.items():
    if model is None:
        print(f"Skipping forecast for {name} due to model fitting error.")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)
        continue
    try:
        forecasts[name] = model.forecast(steps=forecast_steps)
        print(f"Forecast generated for {name}.")
    except Exception as e:
        print(f"Error generating forecast for {name}: {e}")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)

# Create forecast index
last_index = min_length - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot all series with forecasts
print("\nPlotting combined series with forecasts...")
plt.figure(figsize=(14, 8))
colors = ['blue', 'cyan', 'green', 'lime', 'purple', 'magenta']
i = 0
for name, series in series_dict.items():
    plt.plot(series, label=f'{name} Historical', color=colors[i], alpha=0.5)
    plt.plot(forecast_index, forecasts[name], label=f'{name} Forecast', color=colors[i], linestyle='--')
    i += 1
plt.title('Nike, Coca-Cola, Amazon 5-min and 30-min Closing Prices with Forecasts')
plt.legend()
plt.savefig('combined_forecast.png')
plt.show()
plt.close()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    print(f"\nPlotting forecast for {name}...")
    if model is None:
        print(f"Skipping plot for {name} due to model fitting error.")
        return
    try:
        forecast_obj = model.get_forecast(steps=steps)
        forecast = forecast_obj.predicted_mean
        conf_int = forecast_obj.conf_int()
        forecast_index = range(len(series), len(series) + steps)
        plt.figure(figsize=(12, 6))
        plt.plot(series, label=f'{name} Historical')
        plt.plot(forecast_index, forecast, label='Forecast', color='red')
        plt.fill_between(forecast_index,
                         conf_int.iloc[:, 0],
                         conf_int.iloc[:, 1],
                         color='pink',
                         alpha=0.3,
                         label='95% Confidence Interval')
        plt.title(f'{name} Price Forecast')
        plt.legend()
        plt.savefig(f'{name}_forecast.png')
        plt.show()
        plt.close()
        # Forecast interpretation
        last_value = series.iloc[-1]
        mean_forecast = forecast.mean()
        print(f"\nForecast Interpretation for {name}:")
        print(f"Last observed value: {last_value:.2f}")
        print(f"Average forecast value: {mean_forecast:.2f}")
        print(f"Forecast change: {mean_forecast - last_value:.2f}")
        if mean_forecast > last_value:
            print("Trend: Upward forecast trend")
        elif mean_forecast < last_value:
            print("Trend: Downward forecast trend")
        else:
            print("Trend: Flat forecast trend")
        print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")
    except Exception as e:
        print(f"Error plotting forecast for {name}: {e}")

# Generate detailed forecast plots and interpretations
for name, model in arima_models.items():
    plot_forecast(model, series_dict[name], name)

# Perform pairwise cointegration tests for 5-min and 30-min separately
pairs_5m = [
    ("Nike_5min", "CocaCola_5min", nike_5m_close, cocacola_5m_close),
    ("Nike_5min", "Amazon_5min", nike_5m_close, amazon_5m_close),
    ("CocaCola_5min", "Amazon_5min", cocacola_5m_close, amazon_5m_close)
]
pairs_30m = [
    ("Nike_30min", "CocaCola_30min", nike_30m_close, cocacola_30m_close),
    ("Nike_30min", "Amazon_30min", nike_30m_close, amazon_30m_close),
    ("CocaCola_30min", "Amazon_30min", cocacola_30m_close, amazon_30m_close)
]

print("\nCointegration Tests for 5-min Data:")
for name1, name2, series1, series2 in pairs_5m:
    cointegration_test(series1, series2, name1, name2)

print("\nCointegration Tests for 30-min Data:")
for name1, name2, series1, series2 in pairs_30m:
    cointegration_test(series1, series2, name1, name2)

# Print forecast values for next 5 periods
print("\nForecast Values for Next 5 Periods:")
for name, forecast in forecasts.items():
    print(f"\n{name} Forecast Values (next 5 periods):")
    print(forecast[:5])

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, coint
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Upload Excel files for Nike, Coca-Cola, Amazon (5-min and 30-min)
print("Please upload Nike 5-min Excel file (e.g., PY - Nike - 5min.xlsx)")
nike_5m_upload = files.upload()
nike_5m_filename = list(nike_5m_upload.keys())[0]
nike_5m_df = pd.read_excel(nike_5m_filename)

print("Please upload Nike 30-min Excel file (e.g., PY - Nike - 30 min.xlsx)")
nike_30m_upload = files.upload()
nike_30m_filename = list(nike_30m_upload.keys())[0]
nike_30m_df = pd.read_excel(nike_30m_filename)

print("Please upload Coca-Cola 5-min Excel file (e.g., PY - CocaCola - 5 min.xlsx)")
cocacola_5m_upload = files.upload()
cocacola_5m_filename = list(cocacola_5m_upload.keys())[0]
cocacola_5m_df = pd.read_excel(cocacola_5m_filename)

print("Please upload Coca-Cola 30-min Excel file (e.g., PY - CocaCola - 30min.xlsx)")
cocacola_30m_upload = files.upload()
cocacola_30m_filename = list(cocacola_30m_upload.keys())[0]
cocacola_30m_df = pd.read_excel(cocacola_30m_filename)

print("Please upload Amazon 5-min Excel file (e.g., PY - Amazon - 5min.xlsx)")
amazon_5m_upload = files.upload()
amazon_5m_filename = list(amazon_5m_upload.keys())[0]
amazon_5m_df = pd.read_excel(amazon_5m_filename)

print("Please upload Amazon 30-min Excel file (e.g., PY - Amazon - 30 min.xlsx)")
amazon_30m_upload = files.upload()
amazon_30m_filename = list(amazon_30m_upload.keys())[0]
amazon_30m_df = pd.read_excel(amazon_30m_filename)

# Print available columns for verification
print("\nNike 5-min columns:", list(nike_5m_df.columns))
print("Nike 30-min columns:", list(nike_30m_df.columns))
print("Coca-Cola 5-min columns:", list(cocacola_5m_df.columns))
print("Coca-Cola 30-min columns:", list(cocacola_30m_df.columns))
print("Amazon 5-min columns:", list(amazon_5m_df.columns))
print("Amazon 30-min columns:", list(amazon_30m_df.columns))

# Ask user for the correct column name for closing prices
close_column = input("Please enter the column name containing closing prices (press Enter for 'Close'): ") or 'Close'

# Extract closing prices using user-specified column name
try:
    nike_5m_close = nike_5m_df[close_column]
    nike_30m_close = nike_30m_df[close_column]
    cocacola_5m_close = cocacola_5m_df[close_column]
    cocacola_30m_close = cocacola_30m_df[close_column]
    amazon_5m_close = amazon_5m_df[close_column]
    amazon_30m_close = amazon_30m_df[close_column]
except KeyError:
    print(f"Error: Column '{close_column}' not found in one or more DataFrames")
    print("Please check the column names and try again")
    raise

# Ensure all series have the same length
min_length = min(len(nike_5m_close), len(nike_30m_close), len(cocacola_5m_close),
                 len(cocacola_30m_close), len(amazon_5m_close), len(amazon_30m_close))
nike_5m_close = nike_5m_close[:min_length]
nike_30m_close = nike_30m_close[:min_length]
cocacola_5m_close = cocacola_5m_close[:min_length]
cocacola_30m_close = cocacola_30m_close[:min_length]
amazon_5m_close = amazon_5m_close[:min_length]
amazon_30m_close = amazon_30m_close[:min_length]

# Dictionary to store series for easier iteration
series_dict = {
    "Nike_5min": nike_5m_close,
    "Nike_30min": nike_30m_close,
    "CocaCola_5min": cocacola_5m_close,
    "CocaCola_30min": cocacola_30m_close,
    "Amazon_5min": amazon_5m_close,
    "Amazon_30min": amazon_30m_close
}

# Data validation
print("\nData Validation:")
for name, series in series_dict.items():
    print(f"{name}:")
    print(f"  Length: {len(series)}")
    print(f"  NaN count: {series.isna().sum()}")
    print(f"  Infinite values: {np.isinf(series).sum()}")
    print(f"  Variance: {series.var():.4f}")

# Check if min_length is sufficient
if min_length < 50:
    print("Warning: Data length is very short (%d). Cointegration tests may be unreliable." % min_length)

# Random Walk Test
def random_walk_test(series, name):
    print(f"\nRandom Walk Test for {name}:")
    diff = series.diff().dropna()
    if np.var(diff) < 1e-5:
        print(f"{name} resembles a random walk (low variance in differences).")
    else:
        print(f"{name} does not clearly exhibit random walk behavior.")

# Unit Root Test (ADF only)
def unit_root_test(series, name):
    print(f"\nUnit Root Test (ADF) for {name}:")
    adf_result = adfuller(series)
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

# Cointegration Test (Engle-Granger)
def cointegration_test(series1, series2, name1, name2):
    print(f"\nCointegration Test (Engle-Granger) between {name1} and {name2}:")
    try:
        score, p_value, _ = coint(series1, series2)
        print(f'Cointegration test statistic: {score:.4f}')
        print(f'p-value: {p_value:.4f}')
        if p_value < 0.05:
            print(f"Interpretation: {name1} and {name2} are cointegrated.")
        else:
            print(f"Interpretation: {name1} and {name2} are not cointegrated.")
    except Exception as e:
        print(f"Error in cointegration test: {e}")

# Function to find best ARIMA model
def find_best_arima(series, name, max_p=2, max_d=1, max_q=2):
    print(f"Fitting ARIMA for {name}...")
    best_aic = float('inf')
    best_order = None
    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except Exception as e:
                    print(f"  Failed ARIMA({p},{d},{q}) for {name}: {e}")
                    continue
    if best_order is None:
        print(f"Error: No valid ARIMA model found for {name}. Skipping.")
        return None
    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Perform tests and ARIMA modeling for all series
arima_orders = {}
arima_models = {}
print("\nStarting ARIMA modeling...")
for name, series in series_dict.items():
    random_walk_test(series, name)
    unit_root_test(series, name)
    order = find_best_arima(series, name)
    if order is None:
        arima_orders[name] = None
        arima_models[name] = None
        continue
    try:
        model = ARIMA(series, order=order).fit()
        arima_orders[name] = order
        arima_models[name] = model
        print(f"ARIMA model fitted for {name}.")
    except Exception as e:
        print(f"Error fitting final ARIMA model for {name}: {e}")
        arima_orders[name] = order
        arima_models[name] = None

# Forecast next 30 periods
forecast_steps = 30
forecasts = {}
print("\nGenerating forecasts...")
for name, model in arima_models.items():
    if model is None:
        print(f"Skipping forecast for {name} due to model fitting error.")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)
        continue
    try:
        forecasts[name] = model.forecast(steps=forecast_steps)
        print(f"Forecast generated for {name}.")
    except Exception as e:
        print(f"Error generating forecast for {name}: {e}")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)

# Create forecast index
last_index = min_length - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot all series with forecasts
print("\nPlotting combined series with forecasts...")
plt.figure(figsize=(14, 8))
colors = ['blue', 'cyan', 'green', 'lime', 'purple', 'magenta']
i = 0
for name, series in series_dict.items():
    plt.plot(series, label=f'{name} Historical', color=colors[i], alpha=0.5)
    plt.plot(forecast_index, forecasts[name], label=f'{name} Forecast', color=colors[i], linestyle='--')
    i += 1
plt.title('Nike, Coca-Cola, Amazon 5-min and 30-min Closing Prices with Forecasts')
plt.legend()
plt.savefig('combined_forecast.png')
plt.show()
plt.close()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    print(f"\nPlotting forecast for {name}...")
    if model is None:
        print(f"Skipping plot for {name} due to model fitting error.")
        return
    try:
        forecast_obj = model.get_forecast(steps=steps)
        forecast = forecast_obj.predicted_mean
        conf_int = forecast_obj.conf_int()
        forecast_index = range(len(series), len(series) + steps)
        plt.figure(figsize=(12, 6))
        plt.plot(series, label=f'{name} Historical')
        plt.plot(forecast_index, forecast, label='Forecast', color='red')
        plt.fill_between(forecast_index,
                         conf_int.iloc[:, 0],
                         conf_int.iloc[:, 1],
                         color='pink',
                         alpha=0.3,
                         label='95% Confidence Interval')
        plt.title(f'{name} Price Forecast')
        plt.legend()
        plt.savefig(f'{name}_forecast.png')
        plt.show()
        plt.close()
        # Forecast interpretation
        last_value = series.iloc[-1]
        mean_forecast = forecast.mean()
        print(f"\nForecast Interpretation for {name}:")
        print(f"Last observed value: {last_value:.2f}")
        print(f"Average forecast value: {mean_forecast:.2f}")
        print(f"Forecast change: {mean_forecast - last_value:.2f}")
        if mean_forecast > last_value:
            print("Trend: Upward forecast trend")
        elif mean_forecast < last_value:
            print("Trend: Downward forecast trend")
        else:
            print("Trend: Flat forecast trend")
        print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")
    except Exception as e:
        print(f"Error plotting forecast for {name}: {e}")

# Generate detailed forecast plots and interpretations
for name, model in arima_models.items():
    plot_forecast(model, series_dict[name], name)

# Perform pairwise cointegration tests for 5-min and 30-min separately
pairs_5m = [
    ("Nike_5min", "CocaCola_5min", nike_5m_close, cocacola_5m_close),
    ("Nike_5min", "Amazon_5min", nike_5m_close, amazon_5m_close),
    ("CocaCola_5min", "Amazon_5min", cocacola_5m_close, amazon_5m_close)
]
pairs_30m = [
    ("Nike_30min", "CocaCola_30min", nike_30m_close, cocacola_30m_close),
    ("Nike_30min", "Amazon_30min", nike_30m_close, amazon_30m_close),
    ("CocaCola_30min", "Amazon_30min", cocacola_30m_close, amazon_30m_close)
]

print("\nCointegration Tests for 5-min Data:")
for name1, name2, series1, series2 in pairs_5m:
    cointegration_test(series1, series2, name1, name2)

print("\nCointegration Tests for 30-min Data:")
for name1, name2, series1, series2 in pairs_30m:
    cointegration_test(series1, series2, name1, name2)

# Print forecast values for next 5 periods
print("\nForecast Values for Next 5 Periods:")
for name, forecast in forecasts.items():
    print(f"\n{name} Forecast Values (next 5 periods):")
    print(forecast[:5])

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, coint
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Upload Excel files for Nike, Coca-Cola, Amazon (5-min and 30-min)
print("Please upload Nike 5-min Excel file (e.g., PY - Nike - 5min.xlsx)")
nike_5m_upload = files.upload()
nike_5m_filename = list(nike_5m_upload.keys())[0]
nike_5m_df = pd.read_excel(nike_5m_filename)

print("Please upload Nike 30-min Excel file (e.g., PY - Nike - 30 min.xlsx)")
nike_30m_upload = files.upload()
nike_30m_filename = list(nike_30m_upload.keys())[0]
nike_30m_df = pd.read_excel(nike_30m_filename)

print("Please upload Coca-Cola 5-min Excel file (e.g., PY - CocaCola - 5 min.xlsx)")
cocacola_5m_upload = files.upload()
cocacola_5m_filename = list(cocacola_5m_upload.keys())[0]
cocacola_5m_df = pd.read_excel(cocacola_5m_filename)

print("Please upload Coca-Cola 30-min Excel file (e.g., PY - CocaCola - 30min.xlsx)")
cocacola_30m_upload = files.upload()
cocacola_30m_filename = list(cocacola_30m_upload.keys())[0]
cocacola_30m_df = pd.read_excel(cocacola_30m_filename)

print("Please upload Amazon 5-min Excel file (e.g., PY - Amazon - 5min.xlsx)")
amazon_5m_upload = files.upload()
amazon_5m_filename = list(amazon_5m_upload.keys())[0]
amazon_5m_df = pd.read_excel(amazon_5m_filename)

print("Please upload Amazon 30-min Excel file (e.g., PY - Amazon - 30 min.xlsx)")
amazon_30m_upload = files.upload()
amazon_30m_filename = list(amazon_30m_upload.keys())[0]
amazon_30m_df = pd.read_excel(amazon_30m_filename)

# Print available columns for verification
print("\nNike 5-min columns:", list(nike_5m_df.columns))
print("Nike 30-min columns:", list(nike_30m_df.columns))
print("Coca-Cola 5-min columns:", list(cocacola_5m_df.columns))
print("Coca-Cola 30-min columns:", list(cocacola_30m_df.columns))
print("Amazon 5-min columns:", list(amazon_5m_df.columns))
print("Amazon 30-min columns:", list(amazon_30m_df.columns))

# Ask user for the correct column name for closing prices
close_column = input("Please enter the column name containing closing prices (press Enter for 'Close'): ") or 'Close'

# Extract closing prices using user-specified column name
try:
    nike_5m_close = nike_5m_df[close_column]
    nike_30m_close = nike_30m_df[close_column]
    cocacola_5m_close = cocacola_5m_df[close_column]
    cocacola_30m_close = cocacola_30m_df[close_column]
    amazon_5m_close = amazon_5m_df[close_column]
    amazon_30m_close = amazon_30m_df[close_column]
except KeyError:
    print(f"Error: Column '{close_column}' not found in one or more DataFrames")
    print("Please check the column names and try again")
    raise

# Data cleaning: Handle NaN and inf values
print("\nCleaning data for NaN and inf values...")
series_list = [nike_5m_close, nike_30m_close, cocacola_5m_close,
               cocacola_30m_close, amazon_5m_close, amazon_30m_close]
series_names = ["Nike_5min", "Nike_30min", "CocaCola_5min",
                "CocaCola_30min", "Amazon_5min", "Amazon_30min"]
cleaned_series = []

for series, name in zip(series_list, series_names):
    print(f"\nChecking {name}:")
    # Check for NaN and inf
    nan_count = series.isna().sum()
    inf_count = np.isinf(series).sum()
    print(f"  NaN count: {nan_count}")
    print(f"  Infinite values: {inf_count}")

    # Handle NaN values with interpolation
    if nan_count > 0:
        print(f"  Interpolating {nan_count} NaN values in {name}...")
        series = series.interpolate(method='linear', limit_direction='both')

    # Handle inf values by replacing with nearest non-inf value
    if inf_count > 0:
        print(f"  Replacing {inf_count} inf values in {name}...")
        series = series.replace([np.inf, -np.inf], np.nan).interpolate(method='linear', limit_direction='both')

    # Verify cleaning
    nan_count_after = series.isna().sum()
    inf_count_after = np.isinf(series).sum()
    print(f"  After cleaning - NaN count: {nan_count_after}, Infinite values: {inf_count_after}")

    if nan_count_after > 0 or inf_count_after > 0:
        print(f"Error: Could not clean all NaN or inf values in {name}. Please check the data.")
        raise ValueError(f"Cleaning failed for {name}")

    cleaned_series.append(series)

# Ensure all series have the same length after cleaning
min_length = min(len(s) for s in cleaned_series)
print(f"\nEnsuring all series have the same length: {min_length}")
nike_5m_close = cleaned_series[0][:min_length]
nike_30m_close = cleaned_series[1][:min_length]
cocacola_5m_close = cleaned_series[2][:min_length]
cocacola_30m_close = cleaned_series[3][:min_length]
amazon_5m_close = cleaned_series[4][:min_length]
amazon_30m_close = cleaned_series[5][:min_length]

# Dictionary to store series for easier iteration
series_dict = {
    "Nike_5min": nike_5m_close,
    "Nike_30min": nike_30m_close,
    "CocaCola_5min": cocacola_5m_close,
    "CocaCola_30min": cocacola_30m_close,
    "Amazon_5min": amazon_5m_close,
    "Amazon_30min": amazon_30m_close
}

# Data validation
print("\nData Validation:")
for name, series in series_dict.items():
    print(f"{name}:")
    print(f"  Length: {len(series)}")
    print(f"  NaN count: {series.isna().sum()}")
    print(f"  Infinite values: {np.isinf(series).sum()}")
    print(f"  Variance: {series.var():.4f}")

# Check if min_length is sufficient
if min_length < 50:
    print("Warning: Data length is very short (%d). Cointegration tests may be unreliable." % min_length)

# Random Walk Test
def random_walk_test(series, name):
    print(f"\nRandom Walk Test for {name}:")
    diff = series.diff().dropna()
    if np.var(diff) < 1e-5:
        print(f"{name} resembles a random walk (low variance in differences).")
    else:
        print(f"{name} does not clearly exhibit random walk behavior.")

# Unit Root Test (ADF only)
def unit_root_test(series, name):
    print(f"\nUnit Root Test (ADF) for {name}:")
    adf_result = adfuller(series)
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

# Cointegration Test (Engle-Granger)
def cointegration_test(series1, series2, name1, name2):
    print(f"\nCointegration Test (Engle-Granger) between {name1} and {name2}:")
    try:
        score, p_value, _ = coint(series1, series2)
        print(f'Cointegration test statistic: {score:.4f}')
        print(f'p-value: {p_value:.4f}')
        if p_value < 0.05:
            print(f"Interpretation: {name1} and {name2} are cointegrated.")
        else:
            print(f"Interpretation: {name1} and {name2} are not cointegrated.")
    except Exception as e:
        print(f"Error in cointegration test: {e}")

# Function to find best ARIMA model
def find_best_arima(series, name, max_p=2, max_d=1, max_q=2):
    print(f"Fitting ARIMA for {name}...")
    best_aic = float('inf')
    best_order = None
    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except Exception as e:
                    print(f"  Failed ARIMA({p},{d},{q}) for {name}: {e}")
                    continue
    if best_order is None:
        print(f"Error: No valid ARIMA model found for {name}. Skipping.")
        return None
    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Perform tests and ARIMA modeling for all series
arima_orders = {}
arima_models = {}
print("\nStarting ARIMA modeling...")
for name, series in series_dict.items():
    random_walk_test(series, name)
    unit_root_test(series, name)
    order = find_best_arima(series, name)
    if order is None:
        arima_orders[name] = None
        arima_models[name] = None
        continue
    try:
        model = ARIMA(series, order=order).fit()
        arima_orders[name] = order
        arima_models[name] = model
        print(f"ARIMA model fitted for {name}.")
    except Exception as e:
        print(f"Error fitting final ARIMA model for {name}: {e}")
        arima_orders[name] = order
        arima_models[name] = None

# Forecast next 30 periods
forecast_steps = 30
forecasts = {}
print("\nGenerating forecasts...")
for name, model in arima_models.items():
    if model is None:
        print(f"Skipping forecast for {name} due to model fitting error.")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)
        continue
    try:
        forecasts[name] = model.forecast(steps=forecast_steps)
        print(f"Forecast generated for {name}.")
    except Exception as e:
        print(f"Error generating forecast for {name}: {e}")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)

# Create forecast index
last_index = min_length - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot all series with forecasts
print("\nPlotting combined series with forecasts...")
plt.figure(figsize=(14, 8))
colors = ['blue', 'cyan', 'green', 'lime', 'purple', 'magenta']
i = 0
for name, series in series_dict.items():
    plt.plot(series, label=f'{name} Historical', color=colors[i], alpha=0.5)
    plt.plot(forecast_index, forecasts[name], label=f'{name} Forecast', color=colors[i], linestyle='--')
    i += 1
plt.title('Nike, Coca-Cola, Amazon 5-min and 30-min Closing Prices with Forecasts')
plt.legend()
plt.savefig('combined_forecast.png')
plt.show()
plt.close()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    print(f"\nPlotting forecast for {name}...")
    if model is None:
        print(f"Skipping plot for {name} due to model fitting error.")
        return
    try:
        forecast_obj = model.get_forecast(steps=steps)
        forecast = forecast_obj.predicted_mean
        conf_int = forecast_obj.conf_int()
        forecast_index = range(len(series), len(series) + steps)
        plt.figure(figsize=(12, 6))
        plt.plot(series, label=f'{name} Historical')
        plt.plot(forecast_index, forecast, label='Forecast', color='red')
        plt.fill_between(forecast_index,
                         conf_int.iloc[:, 0],
                         conf_int.iloc[:, 1],
                         color='pink',
                         alpha=0.3,
                         label='95% Confidence Interval')
        plt.title(f'{name} Price Forecast')
        plt.legend()
        plt.savefig(f'{name}_forecast.png')
        plt.show()
        plt.close()
        # Forecast interpretation
        last_value = series.iloc[-1]
        mean_forecast = forecast.mean()
        print(f"\nForecast Interpretation for {name}:")
        print(f"Last observed value: {last_value:.2f}")
        print(f"Average forecast value: {mean_forecast:.2f}")
        print(f"Forecast change: {mean_forecast - last_value:.2f}")
        if mean_forecast > last_value:
            print("Trend: Upward forecast trend")
        elif mean_forecast < last_value:
            print("Trend: Downward forecast trend")
        else:
            print("Trend: Flat forecast trend")
        print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")
    except Exception as e:
        print(f"Error plotting forecast for {name}: {e}")

# Generate detailed forecast plots and interpretations
for name, model in arima_models.items():
    plot_forecast(model, series_dict[name], name)

# Perform pairwise cointegration tests for 5-min and 30-min separately
pairs_5m = [
    ("Nike_5min", "CocaCola_5min", nike_5m_close, cocacola_5m_close),
    ("Nike_5min", "Amazon_5min", nike_5m_close, amazon_5m_close),
    ("CocaCola_5min", "Amazon_5min", cocacola_5m_close, amazon_5m_close)
]
pairs_30m = [
    ("Nike_30min", "CocaCola_30min", nike_30m_close, cocacola_30m_close),
    ("Nike_30min", "Amazon_30min", nike_30m_close, amazon_30m_close),
    ("CocaCola_30min", "Amazon_30min", cocacola_30m_close, amazon_30m_close)
]

print("\nCointegration Tests for 5-min Data:")
for name1, name2, series1, series2 in pairs_5m:
    cointegration_test(series1, series2, name1, name2)

print("\nCointegration Tests for 30-min Data:")
for name1, name2, series1, series2 in pairs_30m:
    cointegration_test(series1, series2, name1, name2)

# Print forecast values for next 5 periods
print("\nForecast Values for Next 5 Periods:")
for name, forecast in forecasts.items():
    print(f"\n{name} Forecast Values (next 5 periods):")
    print(forecast[:5])